const ENVS = import.meta.env;

const Envs = {
    FIREBASE_APP_ID: ENVS.VITE_SITE_FIREBASE_APP_ID,
    FIREBASE_API_KEY: ENVS.VITE_SITE_FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: ENVS.VITE_SITE_FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: ENVS.VITE_SITE_FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: ENVS.VITE_SITE_FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: ENVS.VITE_SITE_FIREBASE_MESSAGING_SENDER_ID
}